project:
  type: website
  output-dir: docs 

website:
  title: "QuartoWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: page2.qmd
        text: Page 2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

